/**
 * @packageDocumentation
 * @module HubitatDeviceEvents
 */

/**
 * An enum containing all possible
 * [Hubitat's device capability](https://docs.hubitat.com/index.php?title=Driver_Capability_List)
 * names.
 */
export enum ECapability {
  AccelerationSensor = 'AccelerationSensor',
  Actuator = 'Actuator',
  Alarm = 'Alarm',
  AudioNotification = 'AudioNotification',
  AudioVolume = 'AudioVolume',
  Battery = 'Battery',
  Beacon = 'Beacon',
  Bulb = 'Bulb',

  /**
   * @deprecated Deprecated by Hubitat.
   */
  Button = 'Button',

  CarbonDioxideMeasurement = 'CarbonDioxideMeasurement',
  CarbonMonoxideDetector = 'CarbonMonoxideDetector',
  ChangeLevel = 'ChangeLevel',
  Chime = 'Chime',
  ColorControl = 'ColorControl',
  ColorMode = 'ColorMode',
  ColorTemperature = 'ColorTemperature',
  Configuration = 'Configuration',
  Consumable = 'Consumable',
  ContactSensor = 'ContactSensor',
  DoorControl = 'DoorControl',
  DoubleTapableButton = 'DoubleTapableButton',
  EnergyMeter = 'EnergyMeter',
  EstimatedTimeOfArrival = 'EstimatedTimeOfArrival',
  FanControl = 'FanControl',
  FilterStatus = 'FilterStatus',
  GarageDoorControl = 'GarageDoorControl',
  HealthCheck = 'HealthCheck',
  HoldableButton = 'HoldableButton',
  IlluminanceMeasurement = 'IlluminanceMeasurement',
  ImageCapture = 'ImageCapture',
  Indicator = 'Indicator',
  Initialize = 'Initialize',
  Light = 'Light',
  LightEffects = 'LightEffects',
  LocationMode = 'LocationMode',
  Lock = 'Lock',
  LockCodes = 'LockCodes',
  MediaController = 'MediaController',
  Momentary = 'Momentary',
  MotionSensor = 'MotionSensor',
  MusicPlayer = 'MusicPlayer',
  Notification = 'Notification',
  Outlet = 'Outlet',
  Polling = 'Polling',
  PowerMeter = 'PowerMeter',
  PowerSource = 'PowerSource',
  PresenceSensor = 'PresenceSensor',
  PressureMeasurement = 'PressureMeasurement',
  PushableButton = 'PushableButton',
  Refresh = 'Refresh',
  RelativeHumidityMeasurement = 'RelativeHumidityMeasurement',
  RelaySwitch = 'RelaySwitch',
  ReleasableButton = 'ReleasableButton',
  SamsungTV = 'SamsungTV',
  SecurityKeypad = 'SecurityKeypad',
  Sensor = 'Sensor',
  ShockSensor = 'ShockSensor',
  SignalStrength = 'SignalStrength',
  SleepSensor = 'SleepSensor',
  SmokeDetector = 'SmokeDetector',
  SoundPressureLevel = 'SoundPressureLevel',
  SoundSensor = 'SoundSensor',
  SpeechRecognition = 'SpeechRecognition',
  SpeechSynthesis = 'SpeechSynthesis',
  StepSensor = 'StepSensor',
  Switch = 'Switch',
  SwitchLevel = 'SwitchLevel',
  TV = 'TV',
  TamperAlert = 'TamperAlert',
  Telnet = 'Telnet',
  TemperatureMeasurement = 'TemperatureMeasurement',
  TestCapability = 'TestCapability',
  Thermostat = 'Thermostat',
  ThermostatCoolingSetpoint = 'ThermostatCoolingSetpoint',
  ThermostatFanMode = 'ThermostatFanMode',
  ThermostatHeatingSetpoint = 'ThermostatHeatingSetpoint',
  ThermostatMode = 'ThermostatMode',
  ThermostatOperatingState = 'ThermostatOperatingState',
  ThermostatSchedule = 'ThermostatSchedule',
  ThermostatSetpoint = 'ThermostatSetpoint',
  ThreeAxis = 'ThreeAxis',
  TimedSession = 'TimedSession',
  Tone = 'Tone',
  TouchSensor = 'TouchSensor',
  UltravioletIndex = 'UltravioletIndex',
  Valve = 'Valve',
  VideoCamera = 'VideoCamera',
  VideoCapture = 'VideoCapture',
  VoltageMeasurement = 'VoltageMeasurement',
  WaterSensor = 'WaterSensor',
  WindowShade = 'WindowShade',
  ZwMultichannel = 'ZwMultichannel',
  pHMeasurement = 'pHMeasurement',
}
